### PR TITLE
fixed AttributeError for _nvim_mode_change

### LINKED ISSUE #131: Changing modes crashes the python client
Changing modes crashes the python client in version 0.0.37:
```python
Traceback (most recent call last):
  File "/home/oni-link/pythonmodules/neovim/ui/ui_bridge.py", line 91, in apply_updates
    handler = getattr(self._ui, '_nvim_' + update[0])
AttributeError: 'GtkUI' object has no attribute '_nvim_mode_change'
```
Related to https://github.com/neovim/neovim/pull/2660

### PR DESCRIPTION
**Pull request by diefans**
this should close #131

### CODE REVIEW

**Comment by bfredl** [comment]
scrutinizer issue, let's retry....

**Comment by bfredl** [comment]
LGTM. Would you mind squashing and rebasing to master?

**Comment by diefans** [comment]
...could be that I messed up the rebase...
I can create a new fork and make a new pull request - let me know

**Comment by bfredl** [comment]
I think you did it in reverse, rebased master ontop of your changes. It gets easier if you use a feature branch (instead of using your master branch for a PR).

**Comment by diefans** [comment]
I made a new PR #133

**Pull request closed without merging**
