### PR TITLE
add install_requires 'pyuv'

### PR DESCRIPTION
**Pull request by syswow**
install pyuv by default.

### CODE REVIEW

**Comment by tarruda** [comment]
AFAIK pyuv is not available on pypy, which is why it's an optional dependency

**Comment by syswow** [comment]
@tarruda Hi, I think we need to install pyuv, since python2 doesn't install asyncio by default.

**Comment by syswow** [comment]
on my Ubuntu machine, when I install asyncio, python2 will throw "SyntaxError: invalid syntax".

**Comment by tarruda** [comment]
Thats the trollius package, which is installed for python < 3.4

**Comment by syswow** [comment]
@tarruda ok, thanks.

**Comment by tarruda** [comment]
@syswow I just uploaded a new version, can you try upgrading it?

**Comment by syswow** [comment]
@tarruda  sure, i have upgraded.

**Comment by tarruda** [comment]
are you still experiencing the error?

**Comment by syswow** [comment]
no error
because I made a mistake running `pip2 install asyncio`.

**Comment by syswow** [comment]
@tarruda  But I have a question on example `limit.py`. 
When I try to `:Cmd`, neovim say:
```
Error detected while processing function remote#define#CommandBootstrap:
line    5:
TypeError('command_handler() takes exactly 3 arguments (2 given)',)
```
Do I need to open a new issue? :worried:

**Comment by tarruda** [comment]
Yes, it's a bug in the python host

**Comment by tarruda** [comment]
@syswow it should be fixed in version 0.0.34

**Comment by syswow** [comment]
@tarruda  comfirmed fixed. thanks.

**Comment by syswow** [comment]
@tarruda One more question:
```viml
@neovim.function('Func')
def function_handler(self, args):
    self._increment_calls()
    self.vim.current.line = (
        'Function: Called %d times, args: %s' % (self.calls, args))
```
What is the default scoping prefix of `Func` in `limit.py`? How can I specify the scoping prefix?

**Comment by tarruda** [comment]
> What is the default scoping prefix of Func in limit.py? How can I specify the scoping prefix?

Since the remote plugin infrastructure is implemented in vimscript(autoload/remote), I don't think this is possible(I could be wrong, cc @ZyX-I). 

There is still much room for improvement in [host.vim](https://github.com/neovim/neovim/blob/master/runtime/autoload/remote/host.vim) and [define.vim](https://github.com/neovim/neovim/blob/master/runtime/autoload/remote/define.vim), if you know vimscript and have ideas then consider sending PRs. One feature I considered implementing is  declarative mappings in the remote plugin, something like this:

```python
@neovim.nnoremap('<c-t>')
def mapping_handler(self, args):
    ...
```

This would require implementing `MappingOnChannel`/`MappingOnHost`

**Pull request closed without merging**
