### PR TITLE
Add tox

### PR DESCRIPTION
**Pull request by meiralins**

### CODE REVIEW

**Comment by meiralins** [comment]
So, this PR tests python3.6 in travis and now I guess we could bump a new version given #241 is necessary to run on python3.6.

**Comment by justinmk** [comment]
Is it necessary to run the "flake" build on python 2 and 3? Perhaps we only need the "flake" build on python 3. That would eliminate one of the builds.

**Comment by meiralins** [comment]
I don't think it is. Django for example only uses flake on python3. [django/tox.ini](https://github.com/django/django/blob/master/tox.ini)
I can change it to tox also.

**Comment by justinmk** [comment]
I guess just this needs to be deleted from travis.yml:

```
   include:
     - python: 2.7
       env: CI_TARGET=flake
```

**Comment by justinmk** [comment]
LGTM. Ready?

**Comment by bfredl** [comment]
> we could bump a new version given #241 is necessary to run on python3.6.

:+1: I will release a version after this PR.

**Comment by meiralins** [comment]
:shipit:

**Pull request merged**
