### PR TITLE
Add wrapper for vim_command_output

### PR DESCRIPTION
**Pull request by buztard**

### CODE REVIEW

**Comment by bfredl** [comment]
LGTM. Seems some internal error with scrutinizer, please repush.

**Comment by bfredl** [comment]
Still error with scrutinizer. Ping @tarruda . ( It has "reschedule" button, but looks like only repo owner can use it)

**Comment by tarruda** [comment]
Rescheduled, I've granted you admin access @bfredl (should be able to log in with your gh account)

**Comment by bfredl** [comment]
Hmm, scrutinizer complains on "missing coverage data". I think travis and scrutinizer need to be  restarted in synchrony for it to work. To bad github doesn't have a "retrigger push hooks" button, well, except for that ugly close-and-reopen trick.

**Comment by bfredl** [comment]
Hmm, now it gets 4 out of 6 code coverage chunks. Some issue with timing of scrutinizer relative travis? @tarruda 
Too bad scrutinizer refuses to present the partial results of a partially successfull run; I would suppose styling scrutiny to be independent of coverage data. Perhaps should file bug to scrutinizer?

**Comment by bfredl** [comment]
Merged, thanks. Opened separate PR #113 for the timeout issue.

**Pull request merged**
