### PR TITLE
[RFC] api: make remote objects hashable on their identity

### PR DESCRIPTION
**Pull request by bfredl**
Useful for associating data with a buffer purely on the python side.

### CODE REVIEW

**Comment by bfredl** [comment]
ping @tarruda

**Comment by tarruda** [comment]
:+1: LGTM

**Comment by bfredl** [comment]
merged

**Comment by bfredl** [comment]
If scrutinizer thinks a PR introduces a "major issue" why doesn't it say so until _after_ the PR is merged?

**Comment by tarruda** [comment]
It's supposed to warn in the PR itself

**Comment by tarruda** [comment]
In any case, this is a false positive. Python objects are dynamic and can have attributes added at any time

**Comment by bfredl** [comment]
The "bug" I think is that Remote is not marked as an abstract class/mixin somehow.

**Pull request closed without merging**
