### PR TITLE
[RFC] expose vim_call_function

### PR DESCRIPTION
**Pull request by bfredl**
This exposes a method call syntax for calling vimscript functions

    nvim.viml.MyVimscriptFunction(args)

Not sure `viml` is the best name. And what happens if we support async calls, would it be `nvim.viml_async.Func(...)` or `nvim.viml.Func(..., async=True)`. ?

### CODE REVIEW

**Comment by Shougo** [comment]
It is my desired feature!
Wow!

**Comment by justinmk** [comment]
> Not sure viml is the best name.

Maybe `dispatch` or `dispatcher`?

**Comment by bfredl** [comment]
I also thought of `eval` as +eval is the "official" name for the entire vimscript/viml feature (and is one step less when refactoring old-style calls...) Otherwise `funcs` has a kinda namespacey feeling to it, and is perhaps more transparent when the function is not immediately called ( `vim.funcs.SomeName` )

**Comment by bfredl** [comment]
No more discussion, so let's use `funcs`.

**Pull request merged**
