### PR TITLE
Enable asyncio on window again

### PR DESCRIPTION
**Pull request by bfredl**
Note: doesn't work yet. I will setup the windows WM tomorrow.

Also, getting appveyor on this repo might be a good idea.

### CODE REVIEW

**Comment by bfredl** [comment]
Now it manages to receive `[0, 1, b"poll", []]` message, but for some reason it doesn't seem to reply to it...

**Comment by erw7** [comment]
I think that the buffer of [sys.stderr](https://github.com/neovim/python-client/pull/307/files#diff-9ae4dc3c24e48545593584f05d4705e9R130) is overflowing and the reader thread is blocking. My [branch](https://github.com/neovim/python-client/compare/master...erw7:feature-use-asycnio-on-windows) based on your code works for now.

I can not completion deoplete.vim and denite.vim freezes without reproducibility. It is obviously slower than using pyuv. For the above reasons it seems difficult to routinely use at present.

neovim's functionaltest and python-clien tests succeed.

```
C:\> set TEST_FILE=test/functional/provider/python3_spec.lua
C:\> mingw32-make functionaltest
[  0%] Built target printargs-test
[100%] Built target nvim
[100%] Built target shell-test
[==========] Running tests from scanned files.
[----------] Global test environment setup.
[----------] Running tests from test/functional/provider/python3_spec.lua
[ RUN      ] test/functional/provider/python3_spec.lua @ 22: python3 commands and functions feature test
[       OK ] test/functional/provider/python3_spec.lua @ 22: python3 commands and functions feature test (0.00 ms)
[ RUN      ] test/functional/provider/python3_spec.lua @ 26: python3 commands and functions python3_execute
[       OK ] test/functional/provider/python3_spec.lua @ 26: python3 commands and functions python3_execute (15.00 ms)
[ RUN      ] test/functional/provider/python3_spec.lua @ 31: python3 commands and functions does not truncate error message <1 MB
[       OK ] test/functional/provider/python3_spec.lua @ 31: python3 commands and functions does not truncate error message <1 MB (374.00 ms)
[ RUN      ] test/functional/provider/python3_spec.lua @ 40: python3 commands and functions python3_execute with nested commands
[       OK ] test/functional/provider/python3_spec.lua @ 40: python3 commands and functions python3_execute with nested commands (110.00 ms)
[ RUN      ] test/functional/provider/python3_spec.lua @ 45: python3 commands and functions python3_execute with range
[       OK ] test/functional/provider/python3_spec.lua @ 45: python3 commands and functions python3_execute with range (47.00 ms)
[ RUN      ] test/functional/provider/python3_spec.lua @ 55: python3 commands and functions py3file
[       OK ] test/functional/provider/python3_spec.lua @ 55: python3 commands and functions py3file (31.00 ms)
[ RUN      ] test/functional/provider/python3_spec.lua @ 63: python3 commands and functions py3do
[       OK ] test/functional/provider/python3_spec.lua @ 63: python3 commands and functions py3do (31.00 ms)
[ RUN      ] test/functional/provider/python3_spec.lua @ 82: python3 commands and functions py3eval
[       OK ] test/functional/provider/python3_spec.lua @ 82: python3 commands and functions py3eval (15.00 ms)
[----------] 8 tests from test/functional/provider/python3_spec.lua (51807.00 ms total)

[----------] Global test environment teardown.
[==========] 8 tests from 1 test file ran. (51807.00 ms total)
[  PASSED  ] 8 tests.
[100%] Built target functionaltest
```

When pyuv is used, functionalteste ends at about 4072.00 ms.

```
C:\> python3 -m nose
.....................................................
----------------------------------------------------------------------
Ran 53 tests in 6.820s

OK
Exception ignored in: <bound method BaseEventLoop.__del__ of <ProactorEventLoop running=False closed=False debug=False>>
Traceback (most recent call last):
  File "I:\msys64\mingw64\lib\python3.6\asyncio\base_events.py", line 512, in __del__
  File "I:\msys64\mingw64\lib\python3.6\asyncio\proactor_events.py", line 437, in close
  File "I:\msys64\mingw64\lib\python3.6\asyncio\windows_events.py", line 747, in close
  File "I:\msys64\mingw64\lib\python3.6\logging\__init__.py", line 1294, in debug
  File "I:\msys64\mingw64\lib\python3.6\logging\__init__.py", line 1442, in _log
  File "I:\msys64\mingw64\lib\python3.6\logging\__init__.py", line 1452, in handle
  File "I:\msys64\mingw64\lib\python3.6\logging\__init__.py", line 1514, in callHandlers
  File "I:\msys64\mingw64\lib\python3.6\logging\__init__.py", line 863, in handle
  File "I:\msys64\mingw64\lib\python3.6\logging\__init__.py", line 1069, in emit
  File "I:\msys64\mingw64\lib\python3.6\logging\__init__.py", line 1059, in _open
NameError: name 'open' is not defined
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "I:\msys64\mingw64\lib\python3.6\asyncio\proactor_events.py", line 95, in __del__
  File "I:\msys64\mingw64\lib\python3.6\asyncio\proactor_events.py", line 54, in __repr__
  File "I:\msys64\mingw64\lib\python3.6\asyncio\windows_utils.py", line 152, in fileno
ValueError: I/O operatioon on closed pipe
```

**Comment by erw7** [comment]
I changed to delay the call to data_received, and functionaltest now ends at about 5257.00 ms. It seems that deoplete and denite also started working without problems.

**Comment by bfredl** [comment]
> I think that the buffer of sys.stderr is overflowing a

stderr is not buffered. This should only hurt performance not correctness

> I changed to delay the call to data_receive

Yes, of course the read buffer size should be increased from one. I wanted to get it working (independently of blocking pipe state) before adjusting for performance...

**Comment by erw7** [comment]
Also, I may be saying something strange, but is the reader thread dead before [sys.stderr is redirected to nvim.err_write (data)](https://github.com/neovim/python-client/blob/master/neovim/plugin/script_host.py#L65)? In that case, I think that nothing is output, I applied the following patch to your code and executed `nvim -u NONE --cmd "py3 print('Hello')"`, I got the following output in $NVIM_PYTHON_LOG_FILE.

```diff
--- a/neovim/msgpack_rpc/event_loop/asyncio.py
+++ b/neovim/msgpack_rpc/event_loop/asyncio.py
@@ -124,11 +124,17 @@ class AsyncioEventLoop(BaseEventLoop, asyncio.Protocol,
             self.data_received(data)

     def _stdin_reader(self):
-        sys.stderr.write("a {}\n".format(os.getpid()))
-        while True: #self._active
-            data = sys.stdin.buffer.read(1)
-            sys.stderr.write("b {}\n".format(len(data)))
-            self._loop.call_soon_threadsafe(self.data_received, data)
+        try:
+            sys.stderr.write("a {}\n".format(os.getpid()))
+            while True: #self._active
+                data = sys.stdin.buffer.read(1)
+                sys.stderr.write("b {}\n".format(len(data)))
+                self._loop.call_soon_threadsafe(self.data_received, data)
+        except:
+            import traceback
+            exc_type, exc_value, exc_traceback = sys.exc_info()
+            debug("%s %s %s", exc_type, exc_value,
+                    traceback.format_list(traceback.extract_tb(exc_traceback)))

     def _connect_stdio(self):
         self._loop = loop_cls()
```

```
2018-03-11 11:51:44,033 [DEBUG @ msgpack_stream.py:send:34] 3132 - sent [0, 1, b'vim_get_api_info', ()]
2018-03-11 11:51:44,034 [DEBUG @ base.py:send:117] 3132 - Sending 'b'\x94\x00\x01\xb0vim_get_api_info\x90''
2018-03-11 11:51:44,034 [DEBUG @ asyncio.py:_send:174] 3132 - sent b'\x94\x00\x01\xb0vim_get_api_info\x90' True
2018-03-11 11:51:44,034 [DEBUG @ base.py:run:142] 3132 - Entering event loop
2018-03-11 11:51:44,035 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,035 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,035 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,035 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,035 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,035 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,036 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,036 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,036 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,036 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,036 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,037 [DEBUG @ asyncio.py:_stdin_reader:137] 3132 - <class 'OSError'> [Errno 22] Invalid argument ['  File "C:\\cygwin64\\home\\erw7\\work\\src\\python-client\\neovim\\msgpack_rpc\\event_loop\\asyncio.py", line 130, in _stdin_reader\n    data = sys.stdin.buffer.read(1)\n']
2018-03-11 11:51:44,037 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,037 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,037 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,037 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,037 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
2018-03-11 11:51:44,038 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,038 [DEBUG @ msgpack_stream.py:_on_data:61] 3132 - received message: [0, 1, b'poll', []]
2018-03-11 11:51:44,038 [DEBUG @ async_session.py:_on_request:91] 3132 - received request: b'poll', []
2018-03-11 11:51:44,038 [DEBUG @ msgpack_stream.py:_on_data:59] 3132 - waiting for message...
2018-03-11 11:51:44,038 [DEBUG @ msgpack_stream.py:_on_data:64] 3132 - unpacker needs more data...
```
I suspecting that `sys.stdin.read(1)` may cause an exception, if repeatedly read a file handle specified with PIPE_NOWAIT on Windows.

In my Linux environment processing will progress to the next place even in your code, so maybe there is a completely different reason in your environment, but I hope it will be helpful.

```
...
2018-03-11 12:14:09,144 [DEBUG @ base.py:stop:153] 3147 - Stopped event loop
2018-03-11 12:14:09,144 [DEBUG @ msgpack_stream.py:_on_data:59] 3147 - waiting for message...
2018-03-11 12:14:09,144 [DEBUG @ msgpack_stream.py:_on_data:64] 3147 - unpacker needs more data...
2018-03-11 12:14:09,144 [DEBUG @ base.py:run:144] 3147 - Exited event loop
2018-03-11 12:14:09,172 [INFO @ script_host.py:setup:56] 3147 - install import hook/path
2018-03-11 12:14:09,173 [INFO @ script_host.py:setup:61] 3147 - redirect sys.stdout and sys.stderr
2018-03-11 12:14:09,176 [DEBUG @ session.py:_on_request:205] 3147 - received rpc request, greenlet <greenlet.greenlet object at 0x7f27e36a5210> will handle it
2018-03-11 12:14:09,176 [DEBUG @ host.py:_on_request:90] 3147 - calling request handler for "poll", args: "[]"
2018-03-11 12:14:09,176 [DEBUG @ host.py:_on_request:92] 3147 - request handler for 'poll []' returns: ok
2018-03-11 12:14:09,176 [DEBUG @ session.py:handler:191] 3147 - greenlet <greenlet.greenlet object at 0x7f27e36a5210> finished executing, sending ok as response
2018-03-11 12:14:09,176 [DEBUG @ async_session.py:send:138] 3147 - sending response to request 1: [1, 1, None, 'ok']
2018-03-11 12:14:09,177 [DEBUG @ msgpack_stream.py:send:34] 3147 - sent [1, 1, None, 'ok']
2018-03-11 12:14:09,177 [DEBUG @ base.py:send:117] 3147 - Sending 'b'\x94\x01\x01\xc0\xa2ok''
2018-03-11 12:14:09,177 [DEBUG @ asyncio.py:_send:169] 3147 - sent b'\x94\x01\x01\xc0\xa2ok' True
2018-03-11 12:14:09,264 [WARNING @ session.py:handler:199] 3147 - error caught while processing request 'b'poll' []': Traceback (most recent call last):
  File "/home/erw7/work/python-client/neovim/msgpack_rpc/session.py", line 192, in handler
    response.send(rv)
  File "/home/erw7/work/python-client/neovim/msgpack_rpc/async_session.py", line 139, in send
    self._msgpack_stream.send(resp)
  File "/home/erw7/work/python-client/neovim/msgpack_rpc/msgpack_stream.py", line 35, in send
    self.loop.send(self._packer.pack(msg))
  File "/home/erw7/work/python-client/neovim/msgpack_rpc/event_loop/base.py", line 118, in send
    self._send(data)
  File "/home/erw7/work/python-client/neovim/msgpack_rpc/event_loop/asyncio.py", line 171, in _send
    sys.stdout.buffer.write(data)
AttributeError: 'RedirectStream' object has no attribute 'buffer'
```

**Comment by erw7** [comment]
As you might already know, the explanation of PIPE_NOWAITE of [Microsoft's CreateNamedPipe](https://msdn.microsoft.com/library/windows/desktop/aa365150(v=vs.85).aspx) has the following description.

> Nonblocking mode is enabled. In this mode, ReadFile, WriteFile, and ConnectNamedPipe always return immediately.
>
> Note that nonblocking mode is supported for compatibility with Microsoft LAN Manager version 2.0  and should not be used to achieve asynchronous I/O with named pipes. For more information on asynchronous pipe I/O, see Synchronous and Overlapped Input and Output.

**Comment by bfredl** [comment]
>   sys.stderr is redirected to nvim.err_write (data)? 

Ahyes, that would be a problem, though I would think the deadlock I got was before that, because I never saw that error message in my logs. We should keep private copies of stdout and stderr in the event loop.

> Note that nonblocking mode is supported for compatibility with Microsoft LAN Manager version 2.0 and should not be used to achieve asynchronous I/O with named pipes. For more information on asynchronous pipe I/O, see Synchronous and Overlapped Input and Output.

Indeed, the "main" option forward should be https://github.com/neovim/neovim/pull/8113 (IPC mode didn't work, probably requires both ends to be libuv, so trying a patch for only the overlapped flag now), but we probably should support this thread fallback until nvim 0.2.3 is released.

**Comment by bfredl** [comment]
Progress: now works together with  neovim/neovim#8113

@erw7 I just noticed your latest commit https://github.com/erw7/python-client/commit/4c97b67a229da359ebb73791b06011d168b55d0c, does it work to use stdin even if it hasn't been prepared by nvim?

**Comment by erw7** [comment]
No, My last commit require neovim/neovim#8113.

I think that this(#307) is necessary as a fallback.

**Comment by bfredl** [comment]
I tried also to use the handle trick on stdout but it doesn't work. Guess we can live with blocking writes...

However, the fallback for stdin doesn't seem to work, for some reason the OsError for stdin is not getting propagated out of the loop (as it does just fine for stdout), so the thread code path is never reached...

**Comment by erw7** [comment]
Exception of stdin does not propagate, because it is caught on [line 202 of proactor_events.py](https://github.com/python/cpython/blob/3.6/Lib/asyncio/proactor_events.py#L202).

On my [experiment-fallback-reader-thread branch](https://github.com/erw7/python-client/tree/experiment-fallback-reader-thread), I tried to start the reader thread with connection_lost for the time being. @bfredl What do you think.

Because child_watcher does not support on Windows, [this correspondence](https://github.com/neovim/python-client/commit/ff0c2eba1c16523a440d9f8f304aea43f3b5a7fd) is also necessary.

About stdout, it seems that it is an error trying to read [here](https://github.com/python/cpython/blob/3.6/Lib/asyncio/proactor_events.py#L317). I can not understand what that code is going to do, so I do not know if it can be resolved.

**Comment by erw7** [comment]
After all, On my [experiment-fallback-reader-thread branch](https://github.com/erw7/python-client/tree/experiment-fallback-reader-thread), I changed to use  NtQueryInformationFIle like libuv to decide overlapped pipe. It seems that it is working.

**Comment by erw7** [comment]
I looked at the implementation of windows_utils.Popen, [it passing a duplex pipe](https://github.com/python/cpython/blob/3.6/Lib/asyncio/windows_utils.py#L187).
Therefore, I applied the following patch to https://github.com/neovim/neovim/pull/8113 and tried it.

```diff
diff --git a/src/nvim/event/libuv_process.c b/src/nvim/event/libuv_process.c
index b6f6e545c..c777d6f62 100644
--- a/src/nvim/event/libuv_process.c
+++ b/src/nvim/event/libuv_process.c
@@ -58,7 +58,7 @@ int libuv_process_spawn(LibuvProcess *uvproc)
   if (!proc->out.closed) {
     uvproc->uvstdio[1].flags = UV_CREATE_PIPE | UV_WRITABLE_PIPE;
 #ifdef WIN32
-    uvproc->uvstdio[1].flags |= UV_OVERLAPPED_PIPE;
+    uvproc->uvstdio[1].flags |= UV_READABLE_PIPE | UV_OVERLAPPED_PIPE;
 #endif
     uvproc->uvstdio[1].data.stream = STRUCT_CAST(uv_stream_t,
                                                  &proc->out.uv.pipe);
```

It seems that stdout also started to work with asynchronous writing due to this change.

**Comment by bfredl** [comment]
@erw7 Thanks for looking it up. I will go through your changes and clean this PR up, soon...

**Comment by bfredl** [comment]
Update: with nvim 0.3.0 now works on windows without reader thread. So removed all that.

@erw7 Thanks for all your input. Do you see any potential issue with the current code?

**Comment by erw7** [comment]
@bfredl On Windows, `EventLoopPolicy.set_child_watcher()` is not supported. Therefore, I think that the following patch is also necessary. Some tests will fail, so there may be other problems.

```
diff --git a/neovim/msgpack_rpc/event_loop/asyncio.py b/neovim/msgpack_rpc/event_loop/asyncio.py
index 0679289..59d0504 100644
--- a/neovim/msgpack_rpc/event_loop/asyncio.py
+++ b/neovim/msgpack_rpc/event_loop/asyncio.py
@@ -113,8 +113,9 @@ class AsyncioEventLoop(BaseEventLoop, asyncio.Protocol,
         debug("native stdout connection successful")

     def _connect_child(self, argv):
-        self._child_watcher = asyncio.get_child_watcher()
-        self._child_watcher.attach_loop(self._loop)
+        if os.name != 'nt':
+            self._child_watcher = asyncio.get_child_watcher()
+            self._child_watcher.attach_loop(self._loop)
         coroutine = self._loop.subprocess_exec(self._fact, *argv)
         self._loop.run_until_complete(coroutine)
```

**Comment by bfredl** [comment]
For now the primary goal stdio support so nvim python plugins are supported, if child support has trouble we can fix it later.

**Pull request merged**
