### PR TITLE
[RFC] setup.py: Add optional GUI dependencies.

### LINKED ISSUE #115: python-click dependency required?
I can install and use the python-client (under Python 3) without problems, even without `click` installed. Is it really [required](https://github.com/neovim/python-client/blob/80516570b23b2d539040a1c7e8117adf7cd494f7/setup.py#L7)?

### PR DESCRIPTION
**Pull request by fwalch**
Resolves #115.

### CODE REVIEW

**Comment by Shougo** [comment]
:+1:

**Comment by fwalch** [comment]
Ping @bfredl.

**Comment by bfredl** [comment]
LGTM :+1: merged.

**Comment by fwalch** [comment]
Thanks!

**Comment by Pyrohh** [comment]
@bfredl Given all the recent improvements, could you bump the version?

**Comment by bfredl** [comment]
Sure, if it is as simple as it seems... (bump commit + tag)

**Comment by bfredl** [comment]
I don't think I can upload to PyPI tho, ping @tarruda.

**Pull request merged**
